{% set version = "0.10.1" %}

package:
  name: libcbor
  version: {{ version }}

source:
  url: https://github.com/PJK/libcbor/archive/v{{ version }}.tar.gz
  sha256: e8fa0a726b18861c24428561c80b3c95aca95f468df4e2f3e3ac618be12d3047

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libcbor', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f "${PREFIX}/lib/libcbor${SHLIB_EXT}"

about:
  home: https://github.com/PJK/libcbor/
  license: MIT
  license_file: LICENSE.md
  summary: CBOR protocol implementation for C

extra:
  recipe-maintainers:
    - chrisburr
