{% set version = "0.9.0" %}

package:
  name: libcbor
  version: {{ version }}

source:
  url: https://github.com/PJK/libcbor/archive/v{{ version }}.tar.gz
  sha256: da81e4f9333e0086d4e2745183c7052f04ecc4dbcffcf910029df24f103c15d1

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libcbor', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f "${PREFIX}/lib/libcbor${SHLIB_EXT}"

about:
  home: https://github.com/PJK/libcbor/
  license: MIT
  license_file: LICENSE.md
  summary: CBOR protocol implementation for C

extra:
  recipe-maintainers:
    - chrisburr
